accent = "#d7857f"
cursor = "#ffffff"
foreground = "#ffffff"
background = "#1F211B"
selection_foreground = "#ffffff"
selection_background = "#d7857f"

color0 = "#1F211B"
color1 = "#d75450"
color2 = "#F7D1AB"
color3 = "#F5C498"
color4 = "#d7857f"
color5 = "#c6a49f"
color6 = "#F3B788"
color7 = "#FADFC1"
color8 = "#52554d"
color9 = "#ec9997"
color10 = "#ffffff"
color11 = "#fef4eb"
color12 = "#efc6c3"
color13 = "#e9dad8"
color14 = "#fde9da"
color15 = "#ffffff"
